version: '3.4'

services:
  cloud:
    image: hossammohamed44/cloud:latest
    ports:
      - "9090:80"
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123456nada&"
    ports:
      - "1433:1433"
  front:
    image: hossammohamed44/frontend:latest
    ports:
      - "8001:8001"
